const express=require('express');
const cors=require('cors');
const mongoose=require('mongoose');
const app=express();
app.use(cors());
app.use(express.json());
mongoose.connect("mongodb://127.0.0.1:27017/makemark");
const Todo=mongoose.model("datas",new mongoose.Schema({text:String}));
app.get('/todos',async(req,res)=>res.json(await Todo.find()));
app.post('/todos',async(req,res)=>{const t=await Todo.create({text:req.body.text});res.json(t)});
app.delete('/todos/:id',async(req,res)=>{await Todo.findByIdAndDelete(req.params.id);res.json({ok:true})});
const port=4543;app.listen(port,()=>console.log(`http://localhost:${port}`));
